openapi: "3.0.2"
info:
  title: API Patient
  version: "1.0"
servers:
  - url: https://localhost:8080
tags:
  - name: Patient
    description: Patient-specific data.
paths:
  /patients:
    post:
      tags:
        - Patient
      summary: Create Patient
      operationId: createPatient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PatientFullData'

    get:
      tags:
        - Patient
      summary: List Patients
      operationId: listPatients
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PatientFullData'

  /patients/{patientId}:
    get:
      tags:
        - Patient
      summary: Retrieve Patient
      operationId: getPatient
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PatientFullData'
        '404':
          description: NOT FOUND

    put:
      tags:
        - Patient
      summary: Update Patient
      operationId: updatePatient
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PatientFullData'
        '404':
          description: NOT FOUND

    delete:
      tags:
        - Patient
      summary: Delete Patient
      operationId: deletePatient
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: No Content
        '404':
          description: NOT FOUND

components:
  schemas:
    Patient:
      type: object
      properties:
        firstName:
          type: string
          description: First name of the patient
        lastName:
          type: string
          description: Last name of the patient

    PatientFullData:
      type: object
      properties:
        patientId:
          type: integer
          description: The ID of the patient
          format: int32
        firstName:
          type: string
          description: First name of the patient
        lastName:
          type: string
          description: Last name of the patient
      description: Full data of the patient.
